version: '3'

services:
  i2pvanish_plus:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7657:7657"
      - "7667:7667"
      - "4445:4445"
      - "4444:4444"
    volumes:
      - i2p_config:/home/$I2P_USER/i2p_config
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"            
    environment:
      - DEBIAN_FRONTEND=noninteractive
    restart: unless-stopped

volumes:
  i2p_config: